### PR TITLE
Downsize 'advertising' images 

### PR DESCRIPTION
**Pull request by raccube**

### CODE REVIEW

**Comment by antoinepetty** [comment]
Thanks Karina, this is really good.

I think it's a smidge too much on the three homepage photos but I can't notice it anywhere else
image

**Comment by RealOrangeOne** [comment]
I'd be interesting in seeing if this is something we could do automaticaly, eg https://rbuchberger.github.io/jekyll_picture_tag/

**Comment by PeterJCLaw** [comment]
> I'd be interesting in seeing if this is something we could do automaticaly, eg https://rbuchberger.github.io/jekyll_picture_tag/

While we use GitHub Pages we can't install our own extensions AFAIK.

**Comment by sedders123** [comment]
teams-coding 1x looks pixelated on the sponsor page 
image

**Comment by raccube** [comment]
I resized these with GIMP at first, may have had the interpolation settings wrong.

**Review by sedders123 — APPROVED** [review]

**Pull request merged**
