### PR TITLE
Copy navigation toggle from docs

### PR DESCRIPTION
**Pull request by as2247**
Changed toggle code to match docs toggle code. Fading out has been lost (can be added back if needed).
image

### CODE REVIEW

**Comment by Adimote** [comment]
Does this mean we can get rid of jquery?

**Comment by Adimote** [comment]
Looks like we can, jut remove 
```
<script src="https://code.jquery.com/jquery-3.0.0.min.js"
        integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0="
        crossorigin="anonymous"></script>
``` 
from `includes_/scripts.js` and it's gone!

Thanks for doing this, Alana!

**Comment by as2247** [comment]
> Does this mean we can get rid of jquery?

already on it

**Comment by Adimote** [comment]
Removing jquery will speed up the site load time by 180ms :tada:

**Pull request merged**
