### PR TITLE
Update site post splash

### PR DESCRIPTION
**Pull request by Adimote**
Update the site to remove the splash, and prepare it for current visitors.

This includes:
- Removing the splash screen
- Changing the logos to be the new ones
- Updating the sign-up forms to be the newer mailchimp lists

We still need to:
- Add a blog post

This PR is paired with some changes to the theme, see https://github.com/srobo/brand/pull/1

### CODE REVIEW

**Comment by Adimote** [comment]
Tests seem to be failing for a reason unrelated to this PR, Help! @jimmythompson @PeterJCLaw  and @RealOrangeOne

**Comment by Adimote** [comment]
Oops! just noticed I updated the volunteering and team sign up forms to the wrong lists, DO NOT MERGE until I've fixed them

**Comment by RealOrangeOne** [comment]
Why are there things like updating the ruby version in this PR? THis PR should really do nothing but revert the commits which added the screen.

**Comment by Adimote** [comment]
Oops good catch, was introduced when I reverted the splash page commits

**Comment by Adimote** [comment]
I'm splitting this PR into multiple at the request of Peter

**Pull request closed without merging**
