### PR TITLE
Add a bit more space around the sponsor logos on the homepage

### PR DESCRIPTION
**Pull request by PeterJCLaw**
This is partly based on working with #390, but should be generally useful.

### CODE REVIEW

**Comment by antoinepetty** [comment]
Could you add a screenshot please?

**Comment by PeterJCLaw** [comment]
sponsor-spacing

**Comment by antoinepetty** [comment]
I think we need more horizontal margin to fit the brand guidelines of most big companies

**Comment by PeterJCLaw** [comment]
sponsor-spacing-2

**Review by sedders123 — APPROVED** [review]

**Pull request merged**
