### PR TITLE
Add LinkedIn and Instagram to footer

### LINKED ISSUE #210: Add instagram link and icon to footer
Currently have links to our other socials but not instagram 
image

https://www.instagram.com/student_robotics/

### PR DESCRIPTION
**Pull request by raccube**
- Add title to the social media icons in the footer
- Update Font Awesome to 4.7 so that we have an up to date Instagram icon

Closes #210 

image

### CODE REVIEW

**Comment by RealOrangeOne** [comment]
I feel like we need need these icons in decreasing order of importance, rather than increasing (read: big-endian vs little-endian). 

GItHub, Twitter and YouTube are all highly used by us, Instagram is also fairly regularly used. Facebook and LinkedIn on the other hand, less so. 

Alternatively, alphabetical order might be better?

**Review by RealOrangeOne — DISMISSED** [review]

**Review by PeterJCLaw — APPROVED** [review]
One gotcha to note here is that LinkedIn seems to _require_ you to sign up to see our page.
If there's a setting we can tweak which makes it public we should perhaps do that? Don't think that's a blocker to this PR though.

**Comment by RealOrangeOne** [comment]
(As noted in #276, this should be ported to the docs and competition-website too)

**Comment by raccube** [comment]
Can someone merge this?

**Pull request merged**
