### PR TITLE
Handle urls with slashes in a manner Gerrit copes with

### PR DESCRIPTION
**Pull request by PeterJCLaw**
This applies the same fix here as was applied in puppet at 370157e
(https://srobo.org/cgit/server/puppet.git/commit/?id=370157e84f6).

This should fix https://www.studentrobotics.org/trac/ticket/3023 _yet again_.

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
Note that I'm unable to test this since there is still no mechanism to do so.

**Comment by richardbarlow** [comment]
Seems reasonable. Although I too have not tested this.

**Comment by rspanton** [comment]
It is possible to run locally in docker to test.

**Comment by PeterJCLaw** [comment]
> It is possible to run locally in docker to test.

I'm sure it is, but having spent an afternoon trying to do so (notes attached to #50) I couldn't get it working. @rspanton if you have some insight into how to get it working please could you comment on #50?

**Comment by PeterJCLaw** [comment]
Thanks to @jimmythompson's new patches which make it possible to run docker more easily I've now verified that this does indeed fix the issue.

**Pull request merged**
